### ISSUE TITLE
Couple of Questions

### ISSUE THREAD

**Issue by Tythesly** [Sigourn/morrowind-improved#17]
First off I just have to say that I love your guide format. Its very detailed and makes it easy to follow along without any worry of messing anything up. Ive followed 3 guides out there and no matter what I do it always screws up the game >_<

1. Do you mind if I use the issues section to ask questions? lol

2. Don't think it matters much but the Morrowind Graphics Extender Graphics & In-game tab picture is of an older version. Don't really think it makes a difference besides maybe something was renamed but just thought I would let you know just in case.

3. For my Distant Land Generation my "Use Distant Statics" values for Min Size will not go lower than 150. Any idea why?

4. What made you decide to use GitHub for this guide when there are a lot of different options out there?

5. Is this guide something that you used for yourself and are just typing up what/how you did it or is this something you started fresh and are looking at all the mods out there and figuring out what works best?

6. I know this guide is to try and keep the game as vanilla as possible but I was wondering... Would you ever consider making a guide to make the game look as amazing as possible? Or a guide that makes the game just as fun but completely changes everything about it (new locations, extra quests, etc etc)?

7. Do you have a Patreon so people can donate?

8. Are the optional mods ones that are under the click to expand drop downs?

9. Loading Doors Lock Tune says it requires Morrowind Script Extender but that is not listed on the guide. Will that cause any issues?

**Comment by LucasDelfino92** [comment]
Hi.

1) Not at all, a question may be a potential issue to be solved or a note to be added.

2) It's definitely from an older version, but nothing has changed since.

3) Yep. This is because it's needed to be set to a lower value in the Distant Land Generation process, which the guide doesn't mention (you are the first person to ask, so I guess I'll have to go ahead and add a note there lol).

4) I have no idea to be honest. I think I saw other Morrowind guides in github and went for it. Or was it because I didn't know where to put it, and github was one of the first choices that popped up in Google? Who knows!

5) The former! I've made the mistake of adding mods in the past which I wasn't fully sure of adding, which led to me removing them afterwards. But nothing gamebreaking.

6) Sadly no. Before reading your comment I actually updated the Main page to better explain what this guide is about, most importantly, explaining that it is how I like to play the game. And since I don't really like spending time installing the many, many, many texture replacers available out there, not to mention location and quest mods can add a huge amount of compatibility issues... it's really not gonna happen.

7) Nope.

8) Yep!

9) Morrowind Script Extender is MWSE, which is included in MGE XE. So no worries there!

4 Addendum) For what it's worth, github is useful at letting users ask questions and letting me answer them. :)

**Comment by Tythesly** [comment]
Awesome thank you for replying and the extra info 😄

**Comment by LucasDelfino92** [comment]
No problem!
And I just updated the MGE XE images and instructions.
