### ISSUE TITLE
Getting a error notice. What steps to take?

### ISSUE THREAD

**Issue by Tythesly** [Sigourn/morrowind-improved#19]
![asdfasdfasdfasdfasdf](https://user-images.githubusercontent.com/2800945/129114147-3b171557-12bb-43a0-8dc0-26a339c3d6d5.png)

This is the message I get when I move my mouse over the error symbol

**Comment by LucasDelfino92** [comment]
Hey!

That's just MO2 and Nexus being themselves. You shouldn't worry about it too much, which is why I keep the Version tab hidden since it avoids misinformation like that.

However, you can also right click on the mod, and click "Ignore update" (after you've gone on Nexus and confirmed for yourself that your mod is up to date, of course). This will effectively remove said warning from the mod.
