### ISSUE TITLE
Realistic Repair Add-on question

### ISSUE THREAD

**Issue by Tythesly** [Sigourn/morrowind-improved#25]
Realistic Repair Add-on has a Patch for Purist version so that it works with the addon. Out of curiosity why didnt you use that one?

https://www.nexusmods.com/morrowind/mods/47461?tab=files

**Comment by LucasDelfino92** [comment]
Basically the reason is that BTB's Game Improvements makes many many changes to Arrille: it adds new items for sale, and new spells for sale, AND is already compatible with Patch for Purists. And this would require an additional plugin that would just add the new repair items to Arrille, which I didn't find to be particularly crucial.
