### ISSUE TITLE
Are addendum.md and btb.md compatible and other questions.

### ISSUE THREAD

**Issue by wisp92** [Sigourn/morrowind-improved#38]
I like your guide. I couldn't find the information in the documents, so thought of asking here. Not sure if issues are meant to be used for these kinds of questions:

1. Are addendum.md and btb.md compatible?
2. In general, I don't use many graphic mods so your guide addresses graphic improvements I like but I was wondering is there a good reason not to use some body replacer mod? If I decide to use one, are any particular mods in the guide I should try to find patches. for?

Sorry for the n00b questions. I only played and modded Oblivion and Skyrim before, so I am not sure of the difficulties of modding Morrowind and for usual compatibility issues.

**Comment by LucasDelfino92** [comment]
Hi!

1. Addendum and BTB are compatible, yep. BTB has extra instructions not to use a few mods, since it replaces them with compatible versions.
2. Body replacers are not featured since they tend to have plenty of mesh and texture issues that no one is bothering to fix anymore, which is why this guide omits them. For patches, it is best to simply run TES3Merge as explained at the end of the guide. This solves pretty much every issue you can run into. Note that certain mods, however, are not compatible since no Better Bodies alternative was created for them (such as LeFemm Redacted).

**Comment by wisp92** [comment]
Thank you very much for your shift answer!

**Comment by wisp92** [comment]
I find it annoying that the topic "rules" acts as a spoiler when meeting Caius Cosades. I followed the guide faithfully so I suppose dialogue issues like that either cannot be addressed or you are not aware of a mod that does it. I don't know if the mod [Dialogues Decluttered]( https://www.nexusmods.com/morrowind/mods/48301) helps with that, but I thought of bringing it to your attention because at the very least it might help with the dialogue cluttering. Did you consider this mod in the past? As far as I can see it only needs some changes from Patch for Purists to be forwarded.

**Comment by LucasDelfino92** [comment]
Unfortunately that's one of many errors in Morrowind. There are mods that try to fix such oversights. I suggest mentioning it to Lucevar over at the [LDM - Context Matters](https://www.nexusmods.com/morrowind/mods/48273) Nexus page.
