### ISSUE TITLE
Question regarding Divayth Fyr Puzzle Fixed

### ISSUE THREAD

**Issue by danaYatsuta** [Sigourn/morrowind-improved#63]
The modlist suggests not installing OO patch provided by Divayth Fyr Puzzle Fixed. Is there any particular reason for that?

**Comment by LucasDelfino92** [comment]
Yes, it is really up to you to install the patch or not. The reason why I recommend against installing it is because Divayth Fyr will go hostile if you steal from him, whereas in the vanilla game it is implied he is okay with it. So I recommend skipping the patch to keep the spirit of the vanilla quest.
