### ISSUE TITLE
Correct UV Rocks has a more up-to-date version on Nexus

### ISSUE THREAD

**Issue by sirrus233** [Sigourn/morrowind-improved#8]
The version of Correct UV Rocks in this guide points to a 1.0 version hosted on MW Modding History.
There is a more up to date version hosted here: https://www.nexusmods.com/morrowind/mods/46104

**Comment by LucasDelfino92** [comment]
Thanks for the heads up!
Yes, there's a different version of Correct UV Rocks on Nexus. But most knowledgeable modders agree it's better to stick with the version on Modding History, or to alternatively use Pherim's [WIP Detailed Correct UV Rocks](https://www.nexusmods.com/morrowind/mods/44321?).

**Comment by sirrus233** [comment]
Can you explain why? If you say so, I believe you, but it could be valuable in cases like this to have some sort of call-out regarding the pros/cons of alternatives.

**Comment by LucasDelfino92** [comment]
Basically Patch for Purists and Correct UV Rrocks address issues with these meshes in a different way: PfP lowers rocks, while Correct UV Rrocks "extends" the mesh downwards. And Correct UV Rrocks also leads to worse performance.

**Comment by sirrus233** [comment]
That being the case, why does the guide recommend Correct UV Rocks at all?

**Comment by LucasDelfino92** [comment]
Two reasons:
1. Correct UV Rocks is the original mod found on Morrowind Modding History. Nothing wrong with that one. It is **Correct UV Rrocks** that is problematic, given that it was taken over by a different modder.
2. I recommend Correct UV Rocks because the guide doesn't focus on smoothed meshes, which is what Pherim's mod does. Really, the guide tries its best to stay away from graphical mods, even though I have my personal preferences (like the Wolf Helmet Replacer, the Improved Nordic Iron Helm, or even the Pauldrons Streamlined mod).

**Comment by sirrus233** [comment]
Ahh, I got you. Very informative, thanks!
